// Medical blog posts. Same block format as js/papers.js, plus:
//   { t: 'poster', key }                      a summary poster drawn by js/blogart.js
//   { t: 'art', key, k: 'Figure', n: '1', x } an inline SVG figure from js/blogart.js
// House style: no em dashes.

export const BLOG = [
  {
    id: 'glp1-plastics',
    kind: 'Blog',
    year: '2026',
    title: 'GLP-1 receptor agonists: a practical overview for plastic and reconstructive surgeons',
    subtitle: 'With a mini meta-analysis of gastric ultrasound data',
    tag: 'Perioperative · body contouring',
    summary: 'Half of fasted patients on a GLP-1 receptor agonist have retained gastric contents on ultrasound (pooled OR 11.75), yet aspiration stays rare. What that means on a plastics list, and how the drugs change body contouring: weight stability, nutrition, facial volume and expectations.',
    blocks: [
      { t: 'poster', key: 'glp1' },
      { t: 'p', x: 'Plastic surgery has absorbed the GLP-1 era faster than almost any other specialty, and mostly without saying so. The patient list has changed twice over: a cohort of people presenting for body contouring after 15 to 20% total body weight loss achieved without an operation, and a much larger cohort attending for unrelated procedures who happen to be on semaglutide or tirzepatide and may not volunteer it.' },
      { t: 'p', x: 'Both raise practical questions. This piece covers the perioperative one first, because it has the clearest evidence base and the most immediate consequences, then the reconstructive one, where the evidence is considerably thinner than the enthusiasm.' },
      { t: 'h2', x: '1. The aspiration question' },
      { t: 'p', x: 'GLP-1 receptor agonists delay solid-phase gastric emptying. That is not a side effect; it is part of the mechanism by which they produce satiety. The perioperative concern is whether standard fasting still achieves an empty stomach, and the answer, on imaging, is often no.' },
      { t: 'h3', x: 'A pooled analysis' },
      { t: 'p', x: 'Three prospective gastric ultrasound studies have compared residual gastric content (RGC) in fasted GLP-1 RA users against non-users before elective procedures. I pooled them using a DerSimonian and Laird random-effects model on the log odds ratio.' },
      { t: 'art', key: 'forest', k: 'Figure', n: '1', x: 'Increased residual gastric content on preoperative gastric ultrasound, GLP-1 RA users versus non-users. Pooled random-effects OR 11.75 (95% CI 3.67 to 37.68), p < 0.0001. Q = 4.65, df = 2, p = 0.098; τ² = 0.58; I² = 57%.' },
      { t: 'table', rows: [
        ['Study', 'GLP-1 RA', 'Control', 'OR (95% CI)'],
        ['Sherwin 2023', '7/10 (70%)', '1/10 (10%)', '21.00 (1.78 to 248.11)'],
        ['Sen 2024', '35/62 (56%)', '12/62 (19%)', '5.40 (2.41 to 12.09)'],
        ['Nersessian 2024', '43/107 (40%)', '3/113 (3%)', '24.64 (7.34 to 82.64)'],
        ['Pooled (random effects)', '85/179 (47.5%)', '16/185 (8.6%)', '11.75 (3.67 to 37.68)'],
      ] },
      { t: 'p', x: 'Roughly half of fasted patients on a GLP-1 RA have increased gastric contents on ultrasound, against fewer than one in ten controls. Sen and colleagues reported a 30.5% higher absolute prevalence (95% CI 9.9 to 51.2; adjusted prevalence ratio 2.48, 95% CI 1.23 to 4.97), and, importantly, found no association between the duration of drug interruption and the presence of RGC.' },
      { t: 'p', lead: 'Limitations, stated plainly', x: 'Limitations, stated plainly: Three studies, 364 patients. One contributes ten patients per arm and an implausibly wide interval. Event counts for two studies were back-calculated from reported percentages, so they may be off by one. I² of 57% indicates moderate heterogeneity, which is unsurprising given differences in RGC definition, drug, dose phase and fasting protocol. The pooled estimate should be read as "the direction and rough magnitude are consistent" rather than as a precise effect size.' },
      { t: 'h3', x: 'The gap that matters' },
      { t: 'p', x: 'Imaging findings and clinical events diverge sharply. Retained contents are common; aspiration is not. Reported perioperative aspiration rates in this population sit around 0.1 to 0.2%, and larger analyses have not demonstrated a significant increase over controls. One series recorded a single aspiration event in 404 patients.' },
      { t: 'p', x: 'This gap explains why guidance has moved in the direction it has. The 2023 ASA position, hold daily formulations on the day of surgery and weekly formulations for a week, was a blanket rule issued under uncertainty. The multisociety guidance that followed replaced it with shared decision-making and risk stratification, and the finding that interruption duration does not predict RGC is a large part of why: holding the drug for a week does not reliably empty the stomach, so a blanket hold buys less safety than it costs in glycaemic control and treatment continuity.' },
      { t: 'h3', x: 'What this means in a plastics list' },
      { t: 'p', x: 'The features that raise risk are reasonably consistent across the guidance:' },
      { t: 'ul', items: [
        'Dose-escalation phase rather than maintenance: the highest-risk window',
        'Weekly rather than daily formulations, and higher doses',
        'Active GI symptoms on the day: nausea, bloating, early satiety, vomiting',
        'Co-existing gastroparesis, diabetes, or opioid use',
      ] },
      { t: 'p', x: 'A workable approach, consistent with current multisociety guidance:' },
      { t: 'ol', items: [
        'Ask specifically. "Are you on any weight-loss injections?" Patients frequently do not classify these as medications, particularly when prescribed privately or obtained online. This question belongs on the pre-assessment proforma, not in the anaesthetic room.',
        'Continue the drug in asymptomatic maintenance-phase patients, with a 24-hour clear-liquid diet before the procedure in higher-risk patients.',
        'Assess on the day for symptoms of delayed emptying regardless of how long the drug has been held.',
        'Use gastric POCUS where concern persists and the skill is available. It is the only method that actually answers the question for the patient in front of you.',
        'Adjust the anaesthetic, not the surgery: rapid sequence induction, or regional where the procedure allows. Much of what plastic surgery does under GA could be done under regional or local-plus-sedation, which sidesteps the problem entirely.',
      ] },
      { t: 'p', x: 'The cancellation decision is worth thinking about before it arises. Cancelling a symptomatic patient on the day is defensible. Cancelling every patient on a GLP-1 RA is not, and at current prescribing rates would be unworkable.' },
      { t: 'h2', x: '2. The body contouring question' },
      { t: 'p', x: 'The second cohort is the one reshaping practice.' },
      { t: 'p', x: 'GLP-1-induced weight loss differs from bariatric weight loss in ways that matter surgically. It is often faster relative to the skin\'s capacity to retract. It is achieved without the nutritional counselling infrastructure that surrounds bariatric surgery. And it is reversible: patients who stop regain, which has direct implications for the timing of contouring.' },
      { t: 'p', lead: 'Weight stability before operating', x: 'Weight stability before operating: This is the single most important variable and the one most likely to be compromised. A patient who stops the drug after contouring and regains 10% body weight has had the wrong operation at the wrong time. A patient still actively losing has the same problem in the other direction. Documented stability, ideally 6 to 12 months, should be a prerequisite, and the plan for continuing or stopping the drug should be established preoperatively with whoever is prescribing it.' },
      { t: 'p', x: 'There is early evidence that this matters for complications. A 552-patient study reported in early 2026 found that greater and faster preoperative weight loss was associated with higher complication rates after abdominal body contouring, particularly in patients combining bariatric surgery with GLP-1 therapy. (This study has been reported in the general press; verify the primary publication before citing it formally.)' },
      { t: 'p', lead: 'Nutritional status', x: 'Nutritional status: Reduced intake over months produces protein and micronutrient deficiency that is easy to miss in a patient who looks well. Albumin, iron studies, B12, folate and vitamin D are reasonable pre-contouring bloods, and the threshold for a dietetics referral should be low. Wound healing after a circumferential body lift is not a good place to discover a protein deficit.' },
      { t: 'p', lead: 'Facial volume', x: 'Facial volume: Loss of deep and superficial facial fat pads produces midface hollowing, skin laxity and deepening folds, the phenomenon that acquired a drug\'s brand name in the press. Survey data presented at the 2025 ASDS annual meeting and reported in the aesthetic literature suggest the presentation is common, with midface volume loss the most frequently reported concern. Treatment is the familiar volume-restoration ladder; what is new is the volume of demand and the speed of onset.' },
      { t: 'p', lead: 'Expectations', x: 'Expectations: A 2026 comparative study of psychosocial outcomes found that BODY-Q and FACE-Q improvements after contouring were comparable between GLP-1 and bariatric patients, with no independent effect of weight-loss modality on BODY-Q change (β = 0.12; p = 0.58). But GLP-1 patients showed higher preoperative expectation scores and greater emotional reactivity to residual contour irregularity, and lower baseline psychosocial scores predicted postoperative dissatisfaction (β = −0.34; p = 0.02). The practical reading: the operation works as well, but the consultation has to work harder. A patient whose weight loss felt relatively effortless may carry that expectation into an operation that will leave permanent scars.' },
    ],
  },

  {
    id: 'figure-of-eight',
    kind: 'Blog',
    year: '2026',
    title: 'The figure-of-eight suture for punch biopsy closure: a technique in common use on no comparative evidence',
    subtitle: 'Evidence review and a proposed split-body trial',
    tag: 'Dermatological surgery · trial design',
    summary: 'The figure-of-eight closure is taught, passed on and defended, and nobody has compared it with a simple interrupted suture in skin. What the literature actually contains, the geometric argument, and a 55-patient split-body trial that a single outpatient service could run.',
    blocks: [
      { t: 'poster', key: 'suture' },
      { t: 'p', x: 'Ask three clinicians how they close a 4 mm punch biopsy and you will get three answers: one simple interrupted, two simple interrupted, or a single figure-of-eight. The figure-of-eight is taught informally, passed between trainees, and defended on the grounds that it gives better apposition of a circular defect with one throw.' },
      { t: 'p', x: 'I went looking for the evidence behind that claim. There isn\'t any.' },
      { t: 'h2', x: 'What the literature actually contains' },
      { t: 'p', lead: 'On the figure-of-eight in skin closure', x: 'On the figure-of-eight in skin closure: The only comparative claim I can find is a 2012 technical note in the Annals of the Royal College of Surgeons of England describing the technique for arthroscopy portal wounds. The authors report excellent cosmetic results with no wound complications, and argue that simple interrupted sutures produce a "dumbbell" appearance while mattress sutures roll the edges. There is no control group, no scar scale, no blinding, and no numbers. It is a description of a preference, not evidence.' },
      { t: 'p', lead: 'Everything else is somewhere other than skin', x: 'Everything else is somewhere other than skin: The figure-of-eight literature is dominated by haemostasis after large-bore venous access in electrophysiology and structural heart procedures, where there are randomised trials with hard endpoints. There are also series in aortic valve replacement and bowel anastomosis. None of this transfers: those studies measure haemostasis, leak and prosthesis-patient mismatch, not scar quality.' },
      { t: 'p', lead: 'The adjacent skin evidence is about whether to suture at all', x: 'The adjacent skin evidence is about whether to suture at all: A randomised paired-site study in 82 volunteers compared primary closure with second-intention healing for 4 mm and 8 mm punch biopsies on thighs, upper arms and upper back, assessed blind by three physicians at nine months on a 0 to 100 VAS. Mean scores were 58.9 for primary closure and 57.1 for second intention; median scar area 33 mm² versus 32 mm². For 8 mm biopsies volunteers preferred primary closure; for 4 mm biopsies they had no preference. The authors\' interpretation was that sutured wounds on trunk and limbs tend to heal with suture tracks and scar spread under tension, and explicitly noted the results do not extrapolate to head and neck, where sutured punch wounds generally heal without either.' },
      { t: 'p', x: 'That last point is the one that matters here. If the whole benefit of suturing a small punch site is marginal on the trunk, the marginal difference between two suture techniques is likely to be small, which is exactly the situation in which a properly powered trial is needed, and exactly the situation in which nobody has run one.' },
      { t: 'h2', x: 'The proposed mechanism' },
      { t: 'p', x: 'The argument for the figure-of-eight is geometric.' },
      { t: 'art', key: 'suture', k: 'Figure', n: '1', x: 'A punch produces a circular defect that must be converted to a linear closure. A simple interrupted suture applies a single apposition vector across one diameter; tissue on the perpendicular axis is not directly opposed and may gape, producing the described dumbbell configuration. A figure-of-eight applies tension at four points across two crossing axes. The proposed consequence is more even eversion and less central narrowing.' },
      { t: 'p', x: 'Whether this translates into a visible difference at three or six months is unknown. It is entirely plausible that it does not: scar outcome at a 4 mm site is dominated by tension, anatomical site and individual healing, and the contribution of suture configuration may be swamped by all three. The claim is testable and untested.' },
      { t: 'h2', x: 'A trial that would settle it' },
      { t: 'p', x: 'The design is unusually clean, because the intervention is trivially randomisable and each patient can act as their own control.' },
      { t: 'p', lead: 'Design', x: 'Design: Prospective, within-patient split-body randomised trial. Blinded outcome assessment.' },
      { t: 'p', lead: 'Population', x: 'Population: Adults undergoing two or more 4 mm punch biopsies at anatomically comparable, contralateral or paired sites, on the trunk or proximal limb. Diagnostic punches taken for inflammatory dermatoses provide a natural population. Exclusions: keloid or hypertrophic scarring history, current immunosuppression, anticoagulation, diabetes, active smoking, head and neck sites.' },
      { t: 'p', lead: 'Randomisation', x: 'Randomisation: Site-level, computer-generated, sealed envelope opened after the biopsy is taken. Each patient receives one figure-of-eight and one simple interrupted, both 4-0 or 5-0 monofilament, same operator, same removal day.' },
      { t: 'p', lead: 'Primary outcome', x: 'Primary outcome: Observer POSAS 2.0 total score at six months, scored independently by two blinded assessors from standardised photographs. Inter-rater reliability reported as ICC.' },
      { t: 'p', lead: 'Secondary outcomes', x: 'Secondary outcomes: Patient POSAS at six months; maximum scar width in mm on calibrated photographs at three and six months; closure time in seconds; suture-track visibility (present or absent); dehiscence, infection, bleeding.' },
      { t: 'p', lead: 'Sample size', x: 'Sample size: The minimal clinically important difference on observer POSAS has been debated; a conservative approach is to power for a 0.5 SD standardised difference. For a paired design at 90% power and α = 0.05, that requires approximately 44 pairs. Inflating for 20% loss to follow-up gives 55 patients, which is achievable in a single dermatology or plastics outpatient service over 12 to 18 months.' },
      { t: 'p', lead: 'Analysis', x: 'Analysis: Paired t-test or Wilcoxon signed-rank on within-patient differences, depending on distribution. Pre-specified subgroup by anatomical site.' },
      { t: 'p', lead: 'Governance', x: 'Governance: In the UK this is a randomised comparison of two accepted techniques within routine care and requires full REC approval and informed consent. It does not require an IMP or a CTIMP framework.' },
      { t: 'h2', x: 'Why this is worth doing' },
      { t: 'p', x: 'Small-technique questions are unfashionable and disproportionately useful. A 4 mm punch biopsy is one of the highest-volume procedures in medicine. If one closure technique is even modestly better, the aggregate effect across dermatology, primary care and plastics is substantial, and if the two are equivalent, that is worth knowing too, because it would justify choosing on speed and cost rather than on inherited preference.' },
      { t: 'p', x: 'It is also the kind of study that can actually be completed by a junior trainee: single centre, no funding required beyond photography, no follow-up burden beyond a routine six-month appointment, and a clean, publishable answer either way.' },
      { t: 'h2', x: 'References' },
      { t: 'refs', items: [
        'As-Sultany M, Porter P. A simple suturing technique to close arthroscopy portal wounds. Ann R Coll Surg Engl. 2012;94(6). doi:10.1308/003588412X13373405386015f',
        'Christenson LJ, Phillips PK, Weaver AL, Otley CC. Primary closure vs second-intention treatment of skin punch biopsy sites: a randomized trial. Arch Dermatol. 2005;141(9):1093 to 1099. PMID: 16172305',
        'Zuber TJ. Punch biopsy of the skin. Am Fam Physician. 2002;65(6):1155 to 1158.',
        'Alguire PC, Mathes BM. Skin biopsy techniques for the internist. J Gen Intern Med. (Background reference for closure technique.)',
        'Draaijers LJ, Tempelman FRH, Botman YAM, et al. The Patient and Observer Scar Assessment Scale: a reliable and feasible tool for scar evaluation. Plast Reconstr Surg. 2004;113(7):1960 to 1965.',
      ] },
    ],
  },

  {
    id: 'supratip',
    kind: 'Blog',
    year: '2026',
    title: 'Measuring instead of eyeballing: an intraoperative approach to supratip deformity in open rhinoplasty',
    tag: 'Rhinoplasty',
    summary: 'Supratip deformity is decided in theatre, by eye. A 469-patient series gives a caliper measurement, tip-defining point to anterior septal angle, with thresholds by risk: above 6.0 mm in low-risk noses, above 7.5 mm in high-risk ones. What the number measures, how results settle over a year, and what to take into theatre.',
    blocks: [
      { t: 'poster', key: 'supratip' },
      { t: 'p', x: 'Supratip deformity is among the commonest complications of open rhinoplasty, and it is unusual in being a complication that is almost entirely determined in theatre, by decisions that are currently made by eye.' },
      { t: 'p', x: 'The deformity, fullness of the supratip that leads or equals the tip and produces the pollybeak profile, arises from some combination of under-resection of cartilaginous dorsum at the anterior septal angle, loss of tip projection over time, and supratip scar and soft-tissue thickening. On table, with the skin envelope redraped and swollen, the surgeon judges whether the relationship looks right. Twelve months later the soft tissue has settled and the answer is either yes or no.' },
      { t: 'p', x: 'The case for measuring instead is that a number taken intraoperatively is stable, transferable and auditable in a way that an impression is not.' },
      { t: 'h2', x: 'The evidence for a threshold' },
      { t: 'p', x: 'A 2024 retrospective series in Annals of Plastic Surgery is the most directly useful work on this. Şibar and colleagues at Gazi University reviewed 469 patients who underwent open rhinoplasty between 2018 and 2022, assessing each against a four-parameter risk score (skin thickness, lower lateral cartilage anatomy, amount of hump resection, and soft tissue procedures performed) and recording the intraoperative distance between the tip-defining point (TDP) and the anterior septal angle (ASA).' },
      { t: 'p', x: 'At twelve months, 51 of 469 patients (10.9%) had supratip deformity. Risk scores differed significantly between those who did and did not develop it (p < 0.05). More usefully, the TDP to ASA distance predicted the outcome within risk strata.' },
      { t: 'art', key: 'supratip', k: 'Figure', n: '1', x: 'Intraoperative TDP to ASA distance thresholds by risk stratum. In high-risk cases, deformity probability fell significantly above 7.5 mm and rose significantly below 6.5 mm. In low-risk cases, probability was considerably reduced above 6.0 mm.' },
      { t: 'p', x: 'The authors\' recommendation: keep TDP to ASA above 6.0 mm in low-risk patients and above 7.5 mm in high-risk patients.' },
      { t: 'p', x: 'The gap between the two thresholds is the interesting part. It quantifies something surgeons already believe qualitatively: that thick skin, weak lower lateral cartilages and aggressive hump reduction demand more clearance because the soft tissue will fill the space. A 1.5 mm allowance is small enough to be counterintuitive and large enough to matter on a nose.' },
      { t: 'h2', x: 'What the number is measuring' },
      { t: 'p', x: 'TDP to ASA is a proxy for the space available to the soft-tissue envelope. Supratip fullness develops when scar and subcutaneous tissue occupy the gap between the dorsal septum and the redraped skin. If the tip sits far enough anterior to the anterior septal angle, that fill does not eliminate the break; if it does not, it does.' },
      { t: 'p', x: 'This is why the threshold rises with skin thickness and with the extent of soft-tissue dissection. Both increase the predicted volume of fill. The measurement doesn\'t prevent the fill; it ensures the geometry tolerates it.' },
      { t: 'p', x: 'It also explains why intraoperative judgement is unreliable here. At the point of decision the envelope is oedematous and the tissue is not yet scarred. The surgeon is being asked to predict a twelve-month state from a distorted immediate one, which is precisely the kind of task where a fixed rule outperforms expert impression.' },
      { t: 'h2', x: 'Where this sits alongside conventional analysis' },
      { t: 'p', x: 'Standard rhinoplasty analysis is photographic and external. Goode\'s ratio, the perpendicular from the tip-defining point to a tangent at the alar-facial junction divided by the nasion-to-tip distance, has an ideal range of 0.55 to 0.60. Nasal tip rotation is conventionally around 90° in males and 90 to 95° in females. A modest supratip break, with the tip leading the supratip dorsum, is the aesthetic target.' },
      { t: 'p', x: 'These are planning and assessment tools. They tell you what you want to end up with. TDP to ASA is different in kind: it is an intraoperative control variable, measurable with calipers at the moment the decision is made.' },
      { t: 'p', x: 'They also degrade differently over time, which is worth knowing before promising a patient a result. A 2026 series of 84 primary rhinoplasties measured nasolabial angle and Goode ratio intraoperatively and at 6 and 12 months. The nasolabial angle fell from 105.31° ± 2.92° intraoperatively to 100.82° ± 2.77° at six months and 98.12° ± 2.84° at twelve. Goode ratio fell from 0.608 ± 0.022 to 0.589 ± 0.022 to 0.586 ± 0.022. Most of the change occurred in the first six months (Goode ratio change 0.019 ± 0.010 in the first interval versus 0.003 ± 0.002 in the second).' },
      { t: 'table', rows: [
        ['Measure', 'Intraoperative', '6 months', '12 months'],
        ['Nasolabial angle', '105.31° ± 2.92°', '100.82° ± 2.77°', '98.12° ± 2.84°'],
        ['Goode ratio', '0.608 ± 0.022', '0.589 ± 0.022', '0.586 ± 0.022'],
      ] },
      { t: 'cap', k: 'Table', n: '1', x: 'Settling of tip rotation and projection after primary rhinoplasty (n = 84, 2026 series). Most of the drift happens in the first six months.' },
      { t: 'p', x: 'The practical implication is that the intraoperative result is not the final result, and the drift is predictable enough to plan for. Roughly 7° of derotation and 0.02 of projection loss, mostly in the first six months, is the expected settling, which argues for finishing slightly over-rotated and slightly over-projected, and for the deliberate clearance that the TDP to ASA thresholds describe.' },
      { t: 'h2', x: 'Limitations worth stating' },
      { t: 'p', x: 'The threshold data come from a single centre, retrospectively, with a single surgical team and a patient population whose skin characteristics may not generalise. The risk score has not been externally validated. Ten-point-nine percent is a relatively high deformity rate, which could reflect rigorous twelve-month assessment rather than poor outcomes, but could also mean the thresholds are calibrated to a higher-risk practice than yours.' },
      { t: 'p', x: 'Caliper measurement in a bloody field on a mobile tip is also not as precise as a stated 0.5 mm difference implies. Reporting measurement repeatability would strengthen any attempt to replicate this.' },
      { t: 'h2', x: 'What to take into theatre' },
      { t: 'ol', items: [
        'Score the risk before you start: skin thickness, lower lateral cartilage strength, planned hump resection, planned soft-tissue work.',
        'Measure TDP to ASA with calipers at the point of final tip fixation, not by impression.',
        'Target above 6.0 mm in low-risk and above 7.5 mm in high-risk noses, treating 6.5 mm as a floor in high-risk cases.',
        'Expect settling of roughly 7° of rotation and 0.02 Goode ratio over twelve months, most of it in the first six.',
        'Record the number. A measured intraoperative variable and a twelve-month outcome is an audit, and an audit of thirty of your own cases is more informative about your practice than any published series.',
      ] },
      { t: 'p', x: 'That last point is the real argument for measuring. Eyeballing cannot be audited. A number can.' },
      { t: 'h2', x: 'References' },
      { t: 'refs', items: [
        'Şibar S, Erdal AI, Doruk M, Gündüz N, Özçiler MF. Intraoperative measurement-based approach to supratip deformity in open structural rhinoplasty. Ann Plast Surg. 2024;93(5):551 to 557. doi:10.1097/SAP.0000000000004049. PMID: 38980933',
        'Temporal stability of nasal tip rotation and projection following rhinoplasty using an integrated pentagonal tip support technique. 2026. PMC13303891.',
        'Goode RL. Method of tip projection assessment. In: standard rhinoplasty analysis; ideal ratio 0.55 to 0.60.',
        'Rhinoplasty: clinical examination and photographic assessment. In: Oral and Maxillofacial Surgery for the Clinician. Springer; 2021: ch 38. doi:10.1007/978-981-15-1346-6_38',
        'What is the perfect nose? Lessons learnt from the literature. Rhinology Online. Review of anthropometric ideals including dorsal profile and supratip break.',
      ] },
    ],
  },

  {
    id: 'cied-audit',
    kind: 'Blog',
    year: '2026',
    title: 'Auditing CIED remote monitoring: a protocol you can actually run',
    subtitle: 'Cardiac implantable electronic devices: alert response times and follow-up adherence',
    tag: 'Cardiology · audit',
    summary: 'Remote monitoring solved a clinic-capacity problem and created a data-volume one. A ready-to-run trainee audit of alert review against the 24-hour BHRS standard: the question, the data fields, the analysis, the governance, and the findings you can predict before you start.',
    blocks: [
      { t: 'poster', key: 'cied' },
      { t: 'p', x: 'Cardiology device services are a good target for a trainee audit, for an unglamorous reason: the standards are explicit, the data are already electronic, and the thing being measured is a process rather than an outcome, so a single cycle can plausibly change something.' },
      { t: 'p', x: 'This is a protocol rather than a result. The results have to be yours.' },
      { t: 'h2', x: 'Why remote monitoring, and why now' },
      { t: 'p', x: 'Remote monitoring (RM) of cardiac implantable electronic devices (pacemakers, ICDs, CRT devices and implantable loop recorders) is recommended for ongoing management and became the default for most follow-up after 2020. The shift solved a clinic-capacity problem and created a data-volume one.' },
      { t: 'p', x: 'The scale of that is the crux. In one large cohort of 26,713 patients under remote monitoring, 55% had at least one alert transmission over a single year, generating 82,797 alerts; over 40% of all transmissions were alert-initiated. Every one of those requires skilled human interpretation and a timely decision. A UK Delphi consensus of 115 specialists, published in Heart in 2024, found strong agreement on best practice but its lowest agreement on workload distribution, which is a polite way of saying the profession agrees on what should happen and not on who has the capacity to do it.' },
      { t: 'p', x: 'That mismatch is exactly what an audit is for.' },
      { t: 'h2', x: 'Standards to audit against' },
      { t: 'p', x: 'Two documents give auditable statements.' },
      { t: 'p', lead: 'BHRS Clinical Standards and Guidelines for the Follow Up of CIEDs (June 2022)', x: 'BHRS Clinical Standards and Guidelines for the Follow Up of CIEDs (June 2022): The national reference standard for UK device follow-up. Covers bradycardia devices, ICDs, CRT, ILRs, leadless and subcutaneous devices.' },
      { t: 'p', lead: 'UK Delphi consensus on optimising RM for CIEDs (2024)', x: 'UK Delphi consensus on optimising RM for CIEDs (2024): 114 statements tested for consensus at 75% agreement or more; 79 statements reached 90% or more.' },
      { t: 'p', x: 'From these, the statements that convert cleanly into audit standards:' },
      { t: 'table', rows: [
        ['#', 'Standard', 'Target'],
        ['1', 'Remote monitoring alerts are managed within 24 hours', '100%'],
        ['2', 'All device follow-up centres offer a remote monitoring service', '100%'],
        ['3', 'RM reporting is overseen by an accredited healthcare professional', '100%'],
        ['4', 'Consent for remote data transmission is documented', '100%'],
        ['5', 'A dedicated clinical support resource exists for the RM service', 'Yes / No'],
        ['6', 'A dedicated administrative support resource exists', 'Yes / No'],
        ['7', 'A documented clinical escalation pathway exists and is followed', '100%'],
        ['8', 'Audit is an integral part of the RM service', 'Yes / No'],
      ] },
      { t: 'p', x: 'Standard 1 is the one to build the audit around. It is numeric, time-stamped, clinically meaningful, and almost certainly not being met at 100% anywhere.' },
      { t: 'h2', x: 'Protocol' },
      { t: 'art', key: 'auditLoop', k: 'Figure', n: '1', x: 'The audit cycle built around the 24-hour alert review standard. Each cycle changes one thing so that the re-audit can attribute the result.' },
      { t: 'p', lead: 'Question', x: 'Question: What proportion of remote monitoring alerts at this centre are reviewed and actioned within 24 hours of transmission, and what predicts delay?' },
      { t: 'p', lead: 'Design', x: 'Design: Retrospective observational audit against national standard, followed by intervention and a re-audit cycle.' },
      { t: 'p', lead: 'Sample', x: 'Sample: All alert-initiated transmissions over a defined three-month window. If volume is unmanageable, take a random sample of 200 alerts, sufficient to estimate a proportion of around 80% to within ±5.5% at 95% confidence.' },
      { t: 'p', lead: 'Data fields', x: 'Data fields: listed below, with the source for each.' },
      { t: 'table', rows: [
        ['Field', 'Source', 'Notes'],
        ['Anonymised patient ID', 'Device database', ''],
        ['Device type', 'Device database', 'PPM / ICD / CRT-P / CRT-D / ILR'],
        ['Manufacturer', 'Device database', 'Alert nominal settings differ by manufacturer'],
        ['Alert category', 'Transmission record', 'Lead integrity, battery, AF, VT/VF, HF fluid index, other'],
        ['Alert priority', 'Transmission record', 'Red / yellow per local classification'],
        ['Transmission timestamp', 'Device database', ''],
        ['First review timestamp', 'EPR / device database', 'The primary variable'],
        ['Action taken', 'EPR', 'None / recall / phone / admit / reprogram'],
        ['Time to action', 'Derived', ''],
        ['Day of week of transmission', 'Derived', 'Tests the weekend hypothesis'],
        ['Consent to RM documented', 'EPR', 'Standard 4'],
        ['Reviewer accreditation', 'Staff record', 'Standard 3'],
      ] },
      { t: 'p', lead: 'Primary outcome', x: 'Primary outcome: Proportion of alerts reviewed within 24 hours of transmission.' },
      { t: 'p', lead: 'Secondary outcomes', x: 'Secondary outcomes: Median and IQR time to review; proportion within 24 h by alert priority; proportion within 24 h by day of week; proportion of red alerts actioned within 24 h; documented consent rate.' },
      { t: 'p', lead: 'Analysis', x: 'Analysis: as follows.' },
      { t: 'ul', items: [
        'Proportions with 95% confidence intervals (Wilson method).',
        'Time-to-review as median (IQR). The distribution will be right-skewed, so do not report a mean.',
        'Comparison across day of week by χ², across priority strata by χ² or Fisher\'s exact.',
        'A run chart of weekly compliance over the audit window, with the 24-hour standard as a reference line. Run charts are more useful than a single aggregate figure because they show whether failures are systemic or episodic.',
        'Logistic regression only if you have more than 200 alerts and more than 10 events per predictor. Otherwise report stratified proportions and say why.',
      ] },
      { t: 'p', lead: 'Governance', x: 'Governance: Service evaluation against a national standard using routinely collected data, registered with the local clinical audit department. Not research; no REC application. Anonymise at extraction, not after.' },
      { t: 'h2', x: 'The likely findings, and what to do about them' },
      { t: 'p', x: 'You can predict most of the result before you start, which is not a reason to skip it: the value is in the specific local numbers.' },
      { t: 'p', lead: 'Weekend and bank holiday transmissions', x: 'Weekend and bank holiday transmissions: If alerts arrive seven days a week and the service is staffed five, the 24-hour standard is arithmetically unachievable for Friday-to-Sunday transmissions. This usually accounts for the bulk of breaches and is a staffing question, not a performance one.' },
      { t: 'p', lead: 'Alert burden', x: 'Alert burden: Manufacturer nominal alert settings are not optimised for your service, and BHRS has a specific position statement recommending centres familiarise themselves with nominal alert settings and the differences across manufacturers. A large share of alerts are low-clinical-yield. Reviewing programmed alert thresholds is usually the single highest-impact intervention, because it reduces denominator rather than demanding more throughput.' },
      { t: 'p', lead: 'Consent documentation', x: 'Consent documentation: Frequently missing, particularly in patients implanted before RM became routine. Cheap to fix.' },
      { t: 'p', lead: 'Triage', x: 'Triage: Where no priority triage exists, red and yellow alerts sit in one queue and clinically urgent transmissions wait behind fluid-index notifications.' },
      { t: 'p', x: 'The intervention for cycle two writes itself from whichever of these dominates. Keep it to one change (a triage rule, or an alert-threshold review, or a weekend arrangement) because a re-audit after three simultaneous changes tells you nothing about which one worked.' },
      { t: 'h2', x: 'A note on scope' },
      { t: 'p', x: 'This audit measures a process, not patient outcomes, and it is worth being honest about the limit of that. Faster alert review is assumed to improve outcomes; the evidence that it does is largely indirect. There is observational work suggesting remote monitoring data carries prognostic information (one Manchester series linked device transmission data to ONS mortality outcomes) but that is a different claim from "reviewing alerts within 24 rather than 72 hours changes mortality."' },
      { t: 'p', x: 'Audit against a national standard doesn\'t require you to prove the standard. It requires you to state clearly what you measured and what you didn\'t.' },
      { t: 'h2', x: 'References' },
      { t: 'refs', items: [
        'British Heart Rhythm Society. Clinical Standards and Guidelines for the Follow Up of Cardiac Implantable Electronic Devices (CIEDs) for Cardiac Rhythm Management. June 2022.',
        'Ahmad S, Straw S, Gierula J, et al. Optimising remote monitoring for cardiac implantable electronic devices: a UK Delphi consensus. Heart. 2024. doi:10.1136/heartjnl-2024-324167',
        'British Heart Rhythm Society. Position statement on the programming of remote monitoring alerts. 2024.',
        'Veterans Health Administration National Cardiac Device Surveillance Program: structured, centralized remote monitoring for CIEDs to improve quality of care. PMC12287957.',
        'Remote monitoring data from cardiac implantable electronic devices predicts all-cause mortality. PMC8824524.',
        'Heart Rhythm Society. Expert consensus statement on remote interrogation and monitoring for cardiovascular implantable electronic devices.',
      ] },
    ],
  },
];
